### ISSUE TITLE
Downloaded a solid beige colored wallpaper

### ISSUE THREAD

**Issue by jsstrn** [engineersftw/thegeekpath#20]
When I download the wallpaper all I get is a solid beige colored wallpaper. Is this the expected behavior? If not, what should it be? 

If this is a bug, I could look into fixing it.

**Comment by sayanee** [comment]
Eeks! Thanks for raising an alert! I couldn't reproduce the error. 

![screenshot_2017-02-20_21_18_46](https://cloud.githubusercontent.com/assets/413879/23126577/454ae200-f7b2-11e6-88b7-aebba1a2e45f.jpg)

![screenshot 2017-02-20 21 19 38](https://cloud.githubusercontent.com/assets/413879/23126583/50d6bf5e-f7b2-11e6-9356-9b30dae7bb30.png)

Could you let us know:

1. what's your browser? Chrome / Firefox / others?
- what's your OS? macOS / Windows / others?

**Comment by jsstrn** [comment]
I'm using Firefox 51.0.1 on macOS 10.12.3 with a screen resolution of 3840 x 2400px. There are no errors on the browser console. 

I've also disabled all browser plugins that I thought might be interfering with this, but the problem still persists. 🕵️

However, it works fine on Chrome. 🤔

**Comment by cheeaun** [comment]
Tested working on Firefox Developer Edition 52.0a2

<img width="525" alt="screen shot 2017-02-21 at 9 23 36 am" src="https://cloud.githubusercontent.com/assets/2296/23147136/8e00232e-f817-11e6-9fb7-73a5cf524b1b.png">

@jsstrn can try on your version of Firefox? I'll reopen this issue if still not fixed, thanks!

**Comment by jsstrn** [comment]
Yup.. it's fixed. Thank you @cheeaun!
